#!/bin/bash
stop_rdc() {
    #stop RDC if running
    systemctl stop rdc
    return 0
}

reload_systemd() {
    systemctl daemon-reload
    return 0
}
set -e

case "$1" in
   remove | upgrade )
       stop_rdc
       unlink /lib/systemd/system/rdc.service
       reload_systemd
   ;;
   purge)
   ;;
   *)
       exit 0
   ;;
esac

